version: '3.9'

services:
  fastapi-octave:
    build: .
    container_name: back_modeling_project_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
